FROM node:22-alpine
WORKDIR /app
RUN npm install -g pnpm

COPY package.json pnpm-workspace.yaml pnpm-lock.yaml ./
COPY apps/web/package.json ./apps/web/
COPY apps/worker/package.json ./apps/worker/

RUN pnpm install --frozen-lockfile

COPY apps/web/lib ./apps/web/lib
COPY apps/web/prisma ./apps/web/prisma
COPY apps/worker ./apps/worker
COPY prisma ./prisma

RUN pnpm --filter web exec prisma generate

WORKDIR /app/apps/worker
ENV NODE_ENV=development
CMD ["pnpm", "dev"]
